# Sysbuild configuration file.

# Enable MCUboot using overwrite only mode for this sample.
SB_CONFIG_BOOTLOADER_MCUBOOT=y
SB_CONFIG_MCUBOOT_MODE_SWAP_USING_OFFSET=y

SB_CONFIG_BOOT_ENCRYPTION=y
SB_CONFIG_BOOT_SIGNATURE_TYPE_ED25519=y
SB_CONFIG_BOOT_SIGNATURE_KEY_FILE="${APP_DIR}/keys/signing-key-ed25519.pem"
SB_CONFIG_BOOT_ENCRYPTION_KEY_FILE="${APP_DIR}/keys/encryption-key-x25519.pem"

SB_CONFIG_MERGED_HEX_FILES=y
