CONFIG_LOG=y
CONFIG_LOG_BACKEND_UART=y
CONFIG_REBOOT=y

# CONFIG_LOG_MODE_IMMEDIATE=y

CONFIG_SHELL=y
CONFIG_SHELL_LOG_BACKEND=y

CONFIG_LED_STRIP=y
CONFIG_LED_STRIP_SHELL=y
CONFIG_WS2812_STRIP_SPI=y

CONFIG_LED_STRIP_LOG_LEVEL_DBG=y
CONFIG_SPI_LOG_LEVEL_DBG=y
