on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  release:
    types: [ published ]

name: CI

jobs:
  firmware_rust:
    name: Build Rust Firmware
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Install toolchains
        run: rustup target add thumbv6m-none-eabi

      - name: Build
        working-directory: software/firmware
        run: cargo build --release
