on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  release:
    types: [published]

name: CI

jobs:
  build_firmware_application:
    name: Application Firmware
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install toolchain
        working-directory: firmware
        # Uses `rust-toolchain.toml` to set up toolchain
        run: cargo --version

      - name: Install binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install apt dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: signify-openbsd dfu-util
          version: 1.0

      - name: Install cargo dependencies
        run: cargo binstall -y flip-link cargo-binutils

      - name: Query git version
        run: |
          echo "WORKSPACE_GIT_DESCRIBE=$(git describe --tags --always --dirty)" >> $GITHUB_ENV

      - name: Build
        working-directory: firmware
        run: cargo build -p busylight-application --release

      - name: Create firmware bin file
        working-directory: firmware
        run: |
          cargo objcopy -p busylight-application --release -- -O binary target/busylight.${WORKSPACE_GIT_DESCRIBE}.dfu

      - name: Create firmware hex file
        working-directory: firmware
        run: |
          cargo objcopy -p busylight-application --release -- -O ihex target/busylight.${WORKSPACE_GIT_DESCRIBE}.hex

      #   - name: Sign firmware file
      #     working-directory: firmware/application
      #     run: |
      #       shasum -a 512 -b target/busylight.bin | head -c128 | xxd -p -r > target/message.txt
      #       signify-openbsd -S -s firmware/secrets/key.sec -m target/message.txt -x target/message.txt.sig
      #       cp target/busylight.bin target/busylight.${WORKSPACE_GIT_DESCRIBE}.dfu
      #       tail -n1 target/message.txt.sig | base64 -d -i - | dd ibs=10 skip=1 >> target/busylight.${WORKSPACE_GIT_DESCRIBE}.dfu
      #       dfu-suffix --vid 1209 --pid d9d0 --add "target/busylight.${WORKSPACE_GIT_DESCRIBE}.dfu"
      #       cp target/busylight.hex target/busylight.${WORKSPACE_GIT_DESCRIBE}.hex

      - name: Post-process firmware files
        working-directory: firmware
        run: |
          dfu-suffix --vid 1209 --pid d9d0 --add "target/busylight.${WORKSPACE_GIT_DESCRIBE}.dfu"

      - name: Sanity checks
        working-directory: firmware
        run: |
          export DFU_SIZE=$(stat -c%s "target/busylight.${WORKSPACE_GIT_DESCRIBE}.dfu")
          export HEX_SIZE=$(stat -c%s "target/busylight.${WORKSPACE_GIT_DESCRIBE}.hex")
          echo "DFU: $DFU_SIZE"
          echo "HEX: $HEX_SIZE"
          (( $DFU_SIZE > 10000 ))
          (( $HEX_SIZE > 100000 ))

      - name: Upload firmware dfu file as artifact
        uses: actions/upload-artifact@v7
        with:
          path: firmware/target/busylight.${{env.WORKSPACE_GIT_DESCRIBE}}.dfu
          if-no-files-found: error
          archive: false

      - name: Upload firmware hex file as artifact
        uses: actions/upload-artifact@v7
        with:
          path: firmware/target/busylight.${{env.WORKSPACE_GIT_DESCRIBE}}.hex
          if-no-files-found: error
          archive: false

  test_firmware_application:
    name: Firmware Tests
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Install toolchain
        working-directory: firmware
        # Uses `rust-toolchain.toml` to set up toolchain
        run: cargo --version

      - name: Test
        working-directory: firmware
        run: cargo test-host

  build_firmware_bootloader:
    name: Bootloader Firmware
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install toolchain
        working-directory: firmware
        # Uses `rust-toolchain.toml` to set up toolchain
        run: cargo --version

      - name: Install binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install dependencies
        run: cargo binstall -y flip-link cargo-binutils

      - name: Query git version
        run: |
          echo "WORKSPACE_GIT_DESCRIBE=$(git describe --tags --always --dirty)" >> $GITHUB_ENV

      - name: Build
        working-directory: firmware
        run: |
          cargo objcopy -p busylight-bootloader --release -- -O ihex target/busylight.bootloader.${WORKSPACE_GIT_DESCRIBE}.hex

      - name: Sanity checks
        working-directory: firmware
        run: |
          export HEX_SIZE=$(stat -c%s "target/busylight.bootloader.${WORKSPACE_GIT_DESCRIBE}.hex")
          echo $HEX_SIZE
          (( $HEX_SIZE > 10000 ))

      - name: Upload firmware hex file as artifact
        uses: actions/upload-artifact@v7
        with:
          path: firmware/target/busylight.bootloader.${{env.WORKSPACE_GIT_DESCRIBE}}.hex
          if-no-files-found: error
          archive: false

  build_software_linux:
    name: Host software (linux)
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Install apt dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libudev-dev libglib2.0-dev libgtk-3-dev libxdo-dev
          version: 1.0

      - name: Build
        working-directory: software
        run: cargo build --release

  build_software_windows:
    name: Host software (windows)
    runs-on: windows-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Build
        working-directory: software
        env:
          RUSTFLAGS: "-C target-feature=-crt-static"
        run: |
          cargo build --release --target x86_64-pc-windows-msvc

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: host-tools-windows
          path: |
            software/target/x86_64-pc-windows-msvc/release/busylight.exe
            software/target/x86_64-pc-windows-msvc/release/busylight-cli.exe
          if-no-files-found: error
